@startuml S
left to right direction
!pragma layout smetana
[*] --> Portfolio : Відкриття додатку

Portfolio --> Swap : Натиснення вкладки "Swap"
Portfolio --> Orders : Натиснення вкладки "Orders"

Swap --> Portfolio : Натиснення вкладки "Portfolio"
Swap --> Orders : Натиснення вкладки "Orders"

Orders --> Portfolio : Натиснення вкладки "Portfolio"
Orders --> Swap : Натиснення вкладки "Swap"
@enduml
